linters:
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - depguard
    - dupl
    - errchkjson
    - exportloopref
    - exhaustive
    - goconst
    - gocritic
    - gofmt
    - goimports
    - gomnd
    - gocyclo
    - govet
    - ifshort 
    - ineffassign
    - ireturn
    - lll
    - misspell
    - nilerr
    - nilnil
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - structcheck
    - stylecheck
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - wsl

run:
  issues-exit-code: 1